# Generated by Django 3.2 on 2023-07-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
