# Generated by Django 3.2 on 2023-07-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_alter_purchase_totals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='totals',
            field=models.FloatField(default=None, null=True),
        ),
    ]
