# Generated by Django 3.2 on 2023-07-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_auto_20230706_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='totals',
        ),
    ]
