# Generated by Django 3.2 on 2023-07-25 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_auto_20230725_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_order.order'),
        ),
    ]
