# Generated by Django 3.2 on 2023-07-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_alter_purchase_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
