# Generated by Django 3.2 on 2023-07-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeesmgt', '0002_alter_newemployee_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewEmployee',
        ),
    ]
