# Generated by Django 3.2 on 2023-07-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='current_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='intended_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
