# Generated by Django 3.2 on 2023-07-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgt', '0002_auto_20230712_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='initial_quantity',
        ),
        migrations.AddField(
            model_name='stock',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
