# Generated by Django 3.2 on 2023-07-15 08:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_total', models.FloatField(blank=True, default=0, null=True)),
                ('grand_total', models.FloatField(blank=True, default=0, null=True)),
                ('tax_amount', models.FloatField(blank=True, default=0, null=True)),
                ('tax', models.FloatField(blank=True, default=0, null=True)),
                ('tendered_amount', models.FloatField(blank=True, default=0, null=True)),
                ('amount_change', models.FloatField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='salesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('qty', models.FloatField(blank=True, default=0, null=True)),
                ('total', models.FloatField(blank=True, default=0, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='sales.sales')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount', models.FloatField(blank=True, default=0, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sales')),
            ],
        ),
    ]
