# Generated by Django 3.2 on 2023-07-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_salesitem'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
