# Generated by Django 3.2 on 2023-07-07 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20230705_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sale_id',
        ),
        migrations.RemoveField(
            model_name='salesitems',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='salesitems',
            name='productName',
        ),
        migrations.RemoveField(
            model_name='salesitems',
            name='quantity',
        ),
        migrations.AddField(
            model_name='salesitems',
            name='qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount_change',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='grand_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sub_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='tax_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='tendered_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
