# Generated by Django 3.2 on 2023-07-06 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesitems_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesitems',
            old_name='quantity',
            new_name='qty',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sale_id',
        ),
        migrations.RemoveField(
            model_name='salesitems',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='salesitems',
            name='product',
        ),
        migrations.AlterField(
            model_name='sales',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
