# Generated by Django 3.2 on 2023-07-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20230707_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesitems',
            old_name='sale_id',
            new_name='sale',
        ),
    ]
